### ISSUE TITLE
my friend gets this when opening the exe

### ISSUE THREAD

**Issue by claire-rouge** [Medallyon/eso-discord-rich-presence-client#19]
![bilde](https://user-images.githubusercontent.com/15875197/42693198-a31e3ed6-86ae-11e8-9436-30c1f188b814.png)

**Comment by Medallyon** [comment]
What are the exact steps to reproduce this?
Can you paste the `Details` in here?

Thanks.

**Comment by claire-rouge** [comment]
he just installed the program, then got this he said

details:

System.NullReferenceException: Object reference not set to an instance of an object.
   at ESO_Discord_RichPresence_Client.EsoCharacter..ctor(LuaTable character)
   at ESO_Discord_RichPresence_Client.SavedVariables.ParseLua(String luaTable)
   at ESO_Discord_RichPresence_Client.SavedVariables.Initialise()
   at ESO_Discord_RichPresence_Client.Main.Main_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by claire-rouge** [comment]
I didnt have a problem, neither did my other friend.
just him

**Comment by whisperity** [comment]
It generally looks to me as if the datafile made by ESO was botched by an older version of the addon or a crash.

Exit the game, then just simply delete `C:\Users\<username>\Documents\Elder Scrolls Online\live\SavedVariables\DiscordRichPresence.lua` and log in to the game, and then do a `/reloadui`. The file should appear filled with some actual data this time.

Also, make sure the installed addon corresponds to the one the binary is trying to use.
